branch-defaults:
  master:
    environment: alphaBlog-env
global:
  application_name: Alpha-Blog
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Ruby 2.3 (Passenger
    Standalone)
  default_region: us-west-2
  profile: eb-cli
  sc: git
