# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52095c35eacf168f7fbcc8c7ca5575640a6d86be229009d3467dae9e2cea241f98690fbb26b42fd871ce6473dce9856dac36db7ff51f4eb389695e9be0e38fe6

test:
  secret_key_base: 635c0b5c8718ee28da211e1fd56093534a1abe57265be949c98b42ebf0f779cb6e6aa59b1bf3140729372e71787cd90826159c4e25a40c98acd0d403f93d5754

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
